[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["shutarou-iijima <s.iijima@quo-digital.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
